import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>

        <div>
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div>
            <h3 className={styles.h3}>How to learn Javascript in 2023?</h3>
            <p className={styles.p}>
              JavaScript is the language used to design logic for the web
            </p>
            <button className={styles.btn}> Read More </button>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn TypeScript in 2023?</h3>
            <p className={styles.p}>
              JavaScript is the language used to design logic for the web
            </p>
            <button className={styles.btn}> Read More </button>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn NextJS in 2023?</h3>
            <p className={styles.p}>
              JavaScript is the language used to design logic for the web
            </p>
            <button className={styles.btn}> Read More </button>
          </div>
        </div>
      </main>
    </div>
  );
}
